version: '3'
name: linguacafe-dev

networks:
    linguacafe-dev:
        driver: bridge

services:
    webserver:
        container_name: linguacafe-webserver-dev
        build:
            context: .
            dockerfile: ./docker/PhpDockerfileDev
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html
            - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
        environment:
            PYTHON_CONTAINER_NAME: linguacafe-python-service-dev
            DB_DATABASE: linguacafe-dev
            DB_USERNAME: linguacafe-dev
            DB_PASSWORD: linguacafe-dev
            DB_HOST: linguacafe-database-dev
        ports:
            - "3000:3000"
        networks:
            - linguacafe-dev
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database-dev
        restart: unless-stopped
        tty: true
        ports:
          - "3308:3306"
        volumes:
          - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: linguacafe-dev
            MYSQL_USER: linguacafe-dev
            MYSQL_PASSWORD: linguacafe-dev
            MYSQL_ROOT_PASSWORD: linguacafe-dev
            SERVICE_NAME: linguacafe-dev
        networks:
            - linguacafe-dev
    python:
        container_name: linguacafe-python-service-dev 
        command: /app/manage.py runserver 0.0.0.0:8678
        restart: unless-stopped
        tty: true
        build:
            dockerfile: ./docker/PythonDockerfileDev
        volumes:
            - ./tools/django_server:/app
            - ./storage/app:/var/www/html/storage/app
        networks:
            - linguacafe-dev
